version: '3'

services:
  debug:
    image: curlimages/curl
    command: ["curl", "http:localhost:8080"]
  frontend: 
    build:
      context: ./course-client
    restart: always
    ports:
      - "4201:4200"
    environment:
      BACKEND_API: http://localhost:8080
    networks:
      - frontend
    depends_on:
      - backend
    volumes: 
    - type: bind
      source: ./course-client
      target: /app
  backend:
    build:
      context: ./course-api
    restart: always
    ports: 
      - 8080:8080
    environment:
      MONGO_URL: mongodb://my-db:27017/courses
    networks: 
      - frontend
      - backend
    depends_on:
      - my-db
    volumes:
    - type: bind
      source: ./course-api
      target: /app
  my-db: 
    image: mongo:latest
    restart: always
    expose: 
      - 27017
    volumes: 
      - mongo_data:/data/db
    networks:
      - backend

networks: 
  backend: {}
  frontend: {}

volumes:
  mongo_data: {}